platform:
  - x64
configuration:
  #- Debug
  - Release
  
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  
init:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      git clone -b windows --recursive https://github.com/CapeLeidokos/Leidokos-Testing.git
      cd Leidokos-Testing\appveyor
      dir
      cd %APPVEYOR_BUILD_FOLDER%
      call "%APPVEYOR_BUILD_FOLDER%\Leidokos-Testing\appveyor\init.bat"
      cd C:\msys64\usr\lib
      dir
      
build: Script

build_script:
  - cmd: |
      echo "Running build phase"
      cd %APPVEYOR_BUILD_FOLDER%
      mkdir ktest
      cd ktest
      call "%APPVEYOR_BUILD_FOLDER%\Leidokos-Testing\appveyor\test_kaleidoscope_module.bat"
  