platform:
  - x64
configuration:
  #- Debug
  - Release
  
#environment:
  #APPVEYOR_SAVE_CACHE_ON_ERROR: true
  
init:
  - cmd: |
      cd C:\projects
      git clone -b windows --recursive https://github.com/CapeLeidokos/Leidokos-Testing.git
      cd Leidokos-Testing\appveyor
      call "C:\projects\Leidokos-Testing\appveyor\init.bat"
      
build: Script

build_script:
  - cmd: |
      echo "Running build phase"
      cd %APPVEYOR_BUILD_FOLDER%
      mkdir ktest
      cd ktest
      call "C:\projects\Leidokos-Testing\appveyor\test_kaleidoscope_module.bat"
  