platform:
  - x64
configuration:
  #- Debug
  - Release
  
  
#environment:
  #APPVEYOR_SAVE_CACHE_ON_ERROR: true
  
init:
  - cmd: |
  
      rem Activate the administrator account
      net user Administrator /active:yes
       
      rem Use msys2 for all Unix-Like binaries
      rem
      set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
      
install:
  - cmd: |
      cd C:\projects
      git clone -b windows --recursive https://github.com/CapeLeidokos/Leidokos-Testing.git
      cd Leidokos-Testing\appveyor

      C:\msys64\usr\bin\sh C:\projects\Leidokos-Testing\scripts\prepare_system.sh
      
build: Script

build_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      mkdir ktest
      cd ktest
      C:\msys64\usr\bin\sh C:\projects\Leidokos-Testing\scripts\test_kaleidoscope_module.sh
  