platform:
  - x64
configuration:
  #- Debug
  - Release
  
#environment:
  #APPVEYOR_SAVE_CACHE_ON_ERROR: true
  
install:
  - cmd: |
      cd C:\projects
      git clone -b windows --recursive https://github.com/CapeLeidokos/Leidokos-Testing.git
      cd Leidokos-Testing\appveyor
      cmd /c "C:\projects\Leidokos-Testing\appveyor\init.bat" || EXIT /B 1
      
build: Script

build_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      mkdir ktest
      cd ktest
      cmd /c "C:\projects\Leidokos-Testing\appveyor\test_kaleidoscope_module.bat" || EXIT /B 1
  