platform:
  - x64
configuration:
  #- Debug
  - Release
  
  
#environment:
  #APPVEYOR_SAVE_CACHE_ON_ERROR: true
  
init:
  - cmd: |
  
      rem Activate the administrator account
      net user Administrator /active:yes
      
      set CC=C:\msys64\mingw64\bin\gcc.exe
      set CXX=C:\msys64\mingw64\bin\g++.exe

      rem Use msys2 for all Unix-Like binaries
      rem
      set PATH=C:\msys64\mingw64\bin;%PATH%
       
install:
  - cmd: |
      cd C:\projects
      git clone -b windows --recursive https://github.com/CapeLeidokos/Leidokos-Testing.git
      cd Leidokos-Testing\appveyor
      cmd /c "C:\projects\Leidokos-Testing\appveyor\init.bat" || EXIT /B 1
      
build: Script

build_script:
  - cmd: |
      cd %APPVEYOR_BUILD_FOLDER%
      mkdir ktest
      cd ktest
      runas /user:Administator "cmd /c C:\projects\Leidokos-Testing\appveyor\test_kaleidoscope_module.bat" || EXIT /B 1
  