dist: trusty
sudo: false
os:
  - linux
addons:
  apt:
    packages:
      - libboost-python-dev 
      - cmake
      - python3-pip
      #- python-sphinx
before_script:
  - sudo -H pip3 install sphinx
  #- sudo -H pip install sphinxcontrib-napoleon
script:
  - cd $HOME
  - mkdir -p hardware/keyboardio
  - git clone -b regression_testing --recursive https://github.com/noseglasses/Arduino-Boards.git hardware/keyboardio/avr
  - cd hardware/keyboardio/avr
  - git submodule status
  - cd $HOME
  - mkdir kbw_build
  - cd kbw_build
  - cmake --version
  - cmake
      -DKALEIDOSCOPE_FIRMWARE_SKETCH=$HOME/hardware/keyboardio/avr/libraries/Model01-Firmware/Model01-Firmware.ino
      -DKALEIDOSCOPE_PYTHON_GENERATE_API_DOC=TRUE
      -DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
      $HOME/hardware/keyboardio/avr/libraries/Kaleidoscope-Python
  - make doc
  #- ldd _kaleidoscope.so
  #- nm -C _kaleidoscope.so
  #- ls -l doc/kaleidoscope
  #- cd $HOME
  #- mkdir kbw_test
  #- cd kbw_test
  #- git clone --recursive https://github.com/noseglasses/Kaleidoscope-Testing.git
  #- cmake -DKALEIDOSCOPE_TESTING_TARGET_URL=https://github.com/noseglasses/Kaleidoscope-Python.git ./Kaleidoscope-Testing
  #- cmake --build .
  #- ctest
deploy:
   provider: pages
   skip_cleanup: true
   local_dir: $HOME/kbw_build/doc/kaleidoscope
   github_token: $GITHUB_API_KEY
   on:
      branch: master
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
cache:
ccache: true
