dist: trusty
sudo: required
os:
 - linux
 - osx
 
# Only test direct pushes to master
#
branches:
  only: 
    - master
  
before_install:
   - cd $HOME
   - git clone --recursive https://github.com/CapeLeidokos/Leidokos-Testing.git
   - Leidokos-Testing/travis/before_install.sh

script: skip
    
jobs:
  include:
    - stage: test
      script:
         - cd $HOME
         - mkdir ktest
         - cd ktest
         - $HOME/Leidokos-Testing/travis/test_kaleidoscope_module.sh
      
    - stage: build API documentation
      if: (branch = master) AND (env(TRAVIS_OS_NAME) = linux)
      script:
         # Generates and installs the Python API to gh_pages
         - cd $HOME
         - mkdir -p hardware/keyboardio
         - git clone -b regression_testing --recursive https://github.com/CapeLeidokos/Arduino-Boards.git hardware/keyboardio/avr
         - cd hardware/keyboardio/avr
         - git submodule status
         - cd libraries
         - cp -a $TRAVIS_BUILD_DIR .
         - cd $HOME
         - mkdir kbw_build
         - cd kbw_build
         - cmake --version
         - cmake
               -DKALEIDOSCOPE_FIRMWARE_SKETCH=$HOME/hardware/keyboardio/avr/libraries/Model01-Firmware/Model01-Firmware.ino
               -DLEIDOKOS_PYTHON_GENERATE_API_DOC=TRUE
               -DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
               $HOME/hardware/keyboardio/avr/libraries/Leidokos-Python
         - make 
         - make VERBOSE=1 doc
      deploy:
         provider: pages
         skip_cleanup: true
         local_dir: doc/kaleidoscope
         github_token: $GITHUB_API_KEY
         on:
            branch: master
         
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
    
cache:
ccache: true
