dist: trusty
sudo: false
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-python-dev cmake python-sphinx
script:
  - export SKETCHBOOK_DIR=$HOME
  - cd $HOME
  - mkdir -p hardware/keyboardio
  - git clone --recursive https://github.com/noseglasses/Arduino-Boards.git hardware/keyboardio/avr
  - cd hardware/keyboardio/avr
  - git checkout regression_testing
  - cd $HOME
  - mkdir kbw_build
  - cd kbw_build
  - cmake \
      -DKALEIDOSCOPE_HARDWARE_BASE_PATH=$SKETCHBOOK_DIR/hardware \
      -DKALEIDOSCOPE_LIBRARIES_DIR=$SKETCHBOOK_DIR/hardware/keyboardio/avr/libraries \
      -DKALEIDOSCOPE_FIRMWARE_SKETCH=$SKETCHBOOK_DIR/hardware/keyboardio/avr/libraries/Model01-Firmware/Model01-Firmware.ino \
      $SKETCHBOOK_DIR/hardware/keyboardio/avr/libraries/Kaleidoscope-Python-Wrapper
  - make doc
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
cache:
ccache: true